---
- include: mount_special_devices.yml

- name: Copy executable for qemu (Arm on x86)
  copy: 
   remote_src: yes
   src: /usr/bin/qemu-aarch64-static
   dest: "{{ image_template_mountpoint }}/usr/bin/"
   mode: 0755

- name: Copy software install script for execution within chroot
  template: 
    src: "{{ distro }}_install_software.sh.j2"
    dest: "{{ image_template_mountpoint }}/root/{{ distro }}_install_software.sh"
    mode: 0755

- name: Execute software install in CHROOT
  shell: "chroot {{ image_template_mountpoint }} /bin/bash -c /root/{{ distro }}_install_software.sh"

- include: umount_special_devices.yml

