---
- include: mount_image.yml
  delegate_to: '{{ image_host }}'
  remote_user: "{{ image_host_user }}"
  when: not sparsecopy.stat.exists or force_template_create | bool or force_template_update | bool

- include: umount_image.yml
  delegate_to: '{{ image_host }}'
  remote_user: "{{ image_host_user }}"
  when: not sparsecopy.stat.exists or force_template_create | bool or force_template_update | bool

- include: resize_image.yml
  delegate_to: '{{ image_host }}'
  remote_user: "{{ image_host_user }}"
  when: not sparsecopy.stat.exists or force_template_create | bool or force_template_update | bool

