---
# This playbook does the following:
# 1. Setup and configuration of Linux virtual machine/host for custom image generation

- hosts: virtualmachine
  gather_facts: no
  serial: 1
  roles: 
    - hostconfig
    - fetch-image
    - create-template

  